### ISSUE TITLE
Could you explain how to turn off the default brightness switch?

### ISSUE THREAD

**Issue by AlexeyMatskevich** [pop-os/system76-oled#3]
I installed this package and try to change the brightness, but I get the effect of freezing when I press the keys. I installed this package and try to change the brightness, but I get the effect of freezing when I press the keys until i use the keys again. Thus, I think that both the old and the new applications which responsible for the screen brightness are enabled, do you know how to disable the default on Pop!_os ?

**Comment by jackpot51** [comment]
Are you using a System76 Adder WS? If so, it would be good to have a ticket created so we can pull up your product information. Please see https://support.system76.com/

If you are not, this program is currently only active on the System76 Adder WS.

**Comment by AlexeyMatskevich** [comment]
Hello, thank you for answering me so soon. Unfortunately, there is no way to buy your equipment in my country, so I am not your client. I used this code for Dell XPS 15 7590 OLED and it partially works, I believe that I just wait for the ticket to be resolved in the ubuntu distribution. Thank!
